[package]
name = "hanconv"
version = "0.2.1"
edition = "2021"
description = "Convert between Chinese characters variants."
keywords = ["chinese"]
repository = "https://github.com/fhluo/hanconv"
license = "MIT"

[dependencies]
ahash = "0.8"
clap = { version = "4.5", features = ["derive"] }
encoding_rs = "0.8"
