name: Build Go hanconv

on:
  push:
    branches: [ "main" ]
    paths:
      - 'go/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'go/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Set up Task
        uses: arduino/setup-task@v2

      - name: Build
        run: task go:build
