name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-2025
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Set up Rust
        run: |
          rustup default stable
          rustup update

      - name: Set up Task
        run: winget install --id Task.Task

      - name: Build
        run: |
          task go:build
          task cli:build
