name: Release Go hanconv

on:
  push:
    tags: ["go/v*.*.*"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Set up Task
        uses: arduino/setup-task@v2

      - name: Build
        run: task go:build

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            go/bin/*.exe
